name: solid_principles_v2
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  test: ^1.27.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
